#!/bin/sh
# $Id: roguehunter,v 1.5 2016/12/17 16:53:28 fulford Exp $
# $Source: /src/bfl/usr/local/etc/RCS/roguehunter,v $
# $Revision: 1.5 $
# Author C W Fulford.
# Copyright 2016 (c) C W Fulford.
# Licensed for public use under the LGPL, .
# For assistance contact fulford@fulford.net 0793 572 8612
########################################################################
cmd=`basename $0`
ver=`echo "$Id: roguehunter,v 1.5 2016/12/17 16:53:28 fulford Exp $"|awk '{print $3,$4,$5}'`
syntax="$cmd [-c <configfile>] [-d] [-v]|-V"
while [ $# -gt 0 ] ;do
	case $1 in 
		-d) set -x;debug=0;shift;;
		-v) verbose=:;shift;;
		-V) echo "$cmd $Revision: 1.5 $ $Date: 2016/12/17 16:53:28 $"|awk '{print $1,$3,$6}';exit;;  
	esac
done
log=/var/log/$cmd`date +%w`
touch $log
hour=`date +%H`
[ $hour -lt 1 ] && >$log 
rogues=/tmp/$cmd$$ ;touch $rogues

# NB can't use -ef as UnixWare has irregular number of fields
ps -e |
awk 'NR > 1 {
        split($5,a,":")
        if(a[1] >= 200) {
                if ($6 ~ /smn12/) print $1 >> "'$rogues'"
                else if($6 ~ /nfsd/) nfs=true    
                else print "check",$6,$1,a[1] >>"'$log'"
        }
}'
n=`cat $rogues | wc -l`
if [ $n -gt 0 ];then
	cat $rogues |
	while read pid ;do
	       	ps -ef |
		awk '$2 == '$pid' && $3 > 1 {
			print $3 >>"'$rogues'"
		}'
	done
fi
cat $rogues | 
while read pid ;do
	ps -eo "pid ppid comm" |
	awk '{
		if(($1 == '$pid' && $2 == 1) && ($3 ~ /\-ksh/ || $3 ~ /smn12/)){
			print "killing",$1,$3 >>"'$log'"
			print $1
		}
	}' |
	xargs kill
done
rm $rogues
