#!/bin/sh
# $Id: roguehunter,v 1.8 2017/05/13 10:23:02 fulford Exp fulford $
# $Source: /src/bfl/usr/local/etc/RCS/roguehunter,v $
# $Revision: 1.8 $
# Author C W Fulford.
# Copyright 2016 (c) C W Fulford.
# Licensed for public use under the LGPL, .
# For assistance contact fulford@fulford.net 0793 572 8612
########################################################################
cmd=`basename $0`
ver=`echo "$Id: roguehunter,v 1.8 2017/05/13 10:23:02 fulford Exp fulford $"|awk '{print $3,$4,$5}'`
syntax="$cmd [-c <configfile>] [-d] [-v]|-V"
while [ $# -gt 0 ] ;do
	case $1 in 
		-d) set -x;debug=0;shift;;
		-m) max=$2;shift 2;;
		-v) verbose=:;shift;;
		-V) echo "$cmd $Revision: 1.8 $ $Date: 2017/05/13 10:23:02 $"|awk '{print $1,$3,$6}';exit;;  
	esac
done
log=/var/log/$cmd`date +%w`
max=${max:-50}
[ $verbose ] && echo "$cmd: max = $max" >&2
exit
date=`date "+%b %d"`
ls -l $log |grep -q "$date" || >$log
if [ "$debug" ];then
	echo -n "logfile = `ls -l $log`"
fi
rogues=/tmp/$cmd$$ ;touch $rogues

# NB can't use -ef as UnixWare has irregular number of fields
ps -e |
awk 'NR > 1 {
        split($5,a,":")
        if(a[1] >= '$max') {
                if ($6 ~ /smn12/) print $1 >> "'$rogues'"
                else if($6 ~ /nfsd/) nfs=true    
                else print "check",$6,$1,a[1] >>"'$log'"
        }
}'
n=`cat $rogues | wc -l`
if [ $n -gt 0 ];then
	cat $rogues |
	while read pid ;do
	       	ps -ef |
		awk '$2 == '$pid' && $3 > 1 {
			print $3 >>"'$rogues'"
		}'
	done
fi
cat $rogues | 
while read pid ;do
	ps -eo "pid ppid comm" |
	awk '{
		if($1=='$pid' && (($3 ~ /smn12/)||($2==1 && $2 ~ /\-ksh/))){
			printf("%s %i %s ","killing",$1,$3) >>"'$log'"
			# No time functions available in this awk
			cmd="/bin/ksh >> '$log'"
			print "date" | (cmd)
			close(cmd)
			cmd="xargs kill"
			print $1 |(cmd)
			close(cmd)
			#print $1
		}
	}' 
done 
rm $rogues
